# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2425dea3741e8d04fd448ba7af219198e42759b32657d1ba62e18802b4a8a895287534feea8d4a69b01f0703fd92222e4ae5f846c601b99f4a91d865dca77d91

test:
  secret_key_base: f054602ebecdbdd04b25c1a55beaa7a6365583da4928a701da6fa9cf8554baaa6eedb156ffea14e929ccfc6cdbaf08e6d2f91d3dbd9e4b1b7cb01757d7c7e026

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
